// <auto-generated />
namespace MyMemory.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_steps_study : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_steps_study));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040558221_add_steps_study"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
